name: Lint, Format and Analyze

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Lint
      run: npx eslint . --config .eslintrc.js --ext .js,.jsx,.ts,.tsx

    - name: Format
      run: npx prettier --write "frontend/"

    - name: Analyze
      run: jshint "frontend/"
